sendCloud:
  emailApi: http://api.sendcloud.net/apiv2/mail/send
  smsApi: http://www.sendcloud.net/smsapi/send
spring:
  datasource:
    url: jdbc:mysql://192.168.0.154:3306/channel_database
    username: channel
    password: Channel!@#321
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver