sendCloud:
  emailApi: http://api.sendcloud.net/apiv2/mail/send
  smsApi: http://www.sendcloud.net/smsapi/send
  createSmsTemplate: http://www.sendcloud.net/smsapi/addsms
  submitSmsTemplate: http://www.sendcloud.net/smsapi/submitsms
  checkSmsTemplate: http://www.sendcloud.net/smsapi/get
  deleteSmsTemplate: http://www.sendcloud.net/smsapi/deletesms
  updateSmsTemplate: http://www.sendcloud.net/smsapi/updatesms
spring:
  datasource:
    url: jdbc:mysql://192.168.0.154:3306/channel_database?useUnicode=true&characterEncoding=utf8
    username: channel
    password: Channel!@#321
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.0.156
    port: 6380
    database: 2
  rocketMQ:
    namesrvAddr: 192.168.0.156:9876
    producer:
      instanceName: message_send_service_producer
    consumer:
      instanceName: message_send_service_consumer
      subscribe: EMAIL_TASK:*
# 更多数据源
custom:
  datasource:
    names: geeker
    geeker:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.0.154:3306/geeker?useUnicode=true&characterEncoding=utf8
      username: geeker
      password: Geeker!@#2017
      type: com.alibaba.druid.pool.DruidDataSource