spring:
  http:
    encoding:
      charset: utf-8
      forceResponse: true
      forceRequest: true
  redis:
    host: 192.168.0.156
    port: 6380
    database: 1

server:
  port: 8020

wx.secret.redis.store.name: WX_SEC_STORE