eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  dashboard:
    enabled: true
  instance:
    namespace: worken
    prefer-ip-address: false
  server:
    enable-self-preservation: false
    disable-transparent-fallback-to-other-region: true
logging:
  level: off
spring:
  redis:
    host: 192.168.0.156
    port: 6380
    database: 11


---
spring:
  profiles: default
server:
  port: 5555
eureka:
  client:
     serviceUrl:
        prd: http://dc-hadoop156:${server.port}/eureka/
     region: hkdw
     availability-zones:
        hkdw: prd


---
spring:
  profiles: test
server:
  port: 5545
eureka:
  client:
     serviceUrl:
        dev: http://dc-hadoop156:${server.port}/eureka/
     region: hkdw-dev
     availability-zones:
        hkdw-dev: dev
  server:
    remote-region-urls-with-name:
      hkdw-prd: http://dc-hadoop156:5555/eureka/
      product-environment: http://dc-hadoop156:5555/eureka/
    remoteRegionAppWhitelist:
      global: CALL-SERVICE,CALLBACK-SERVER,CLOUD-CONTROL-SERVICE,MESSAGE-SEND-SERVICE,SERVICE-PARSER,SERVICE-PARSERHTML,SERVICE-PAY,SERVICE-PUSH,URL-SHORT-SERVICE,WX-CENTER-SERVICE,WX-SERVICE-SERVICE,FILE-SERVICE


---
spring:
  profiles: release
server:
  port: 5565
eureka:
  client:
     serviceUrl:
        dev: http://dc-hadoop156:${server.port}/eureka/
     region: hkdw-dev
     availability-zones:
        hkdw-dev: dev
  server:
    remote-region-urls-with-name:
      hkdw-prd: http://dc-hadoop156:5555/eureka/
      product-environment: http://dc-hadoop156:5555/eureka/
    remoteRegionAppWhitelist:
      global: CALL-SERVICE,CALLBACK-SERVER,CLOUD-CONTROL-SERVICE,MESSAGE-SEND-SERVICE,SERVICE-PARSER,SERVICE-PARSERHTML,SERVICE-PAY,SERVICE-PUSH,URL-SHORT-SERVICE,WX-CENTER-SERVICE,WX-SERVICE-SERVICE,FILE-SERVICE


---
spring:
  profiles: peer1
server:
  port: 1111
eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
        defaultZone: http://peer2:1112/eureka/,http://peer3:1113/eureka/
    region: peer1
  server:
    remote-region-urls-with-name:
      hkdw: http://dc-hadoop156:5555/eureka/
---
spring:
  profiles: peer2
server:
  port: 1112
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
        defaultZone: http://peer3:1113/eureka/,http://peer1:1111/eureka/
    region: peer2

---
spring:
  profiles: peer3
server:
  port: 1113
eureka:
  instance:
    hostname: peer3
  client:
    serviceUrl:
        defaultZone: http://peer1:1111/eureka/,http://peer2:1112/eureka/
    region: peer3