eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
  dashboard:
    enabled: true
  instance:
    namespace: worken
security:
  basic:
    enabled: true #开启认证
  user:
    name: admin
    password: 123456