eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  dashboard:
    enabled: true
  instance:
    namespace: worken
    prefer-ip-address: false
  server:
    enable-self-preservation: false
logging:
  level: off

---
spring:
  profiles: default
server:
  port: 5555
eureka:
  client:
     serviceUrl:
        prd: http://dc-hadoop156:${server.port}/eureka/
     region: hkdw
     availability-zones:
        hkdw: prd


---
spring:
  profiles: test
server:
  port: 5545
eureka:
  client:
     serviceUrl:
        dev: http://dc-hadoop156:${server.port}/eureka/
     region: hkdw-dev
     availability-zones:
        hkdw-dev: dev

---
spring:
  profiles: peer1
server:
  port: 1111
eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
        defaultZone: http://peer2:1112/eureka/,http://peer3:1113/eureka/
    region: peer1

---
spring:
  profiles: peer2
server:
  port: 1112
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
        defaultZone: http://peer3:1113/eureka/,http://peer1:1111/eureka/
    region: peer2

---
spring:
  profiles: peer3
server:
  port: 1113
eureka:
  instance:
    hostname: peer3
  client:
    serviceUrl:
        defaultZone: http://peer1:1111/eureka/,http://peer2:1112/eureka/
    region: peer3