server:
  port: 1111
eureka:
  instance:
    hostname: 192.168.5.2
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  dashboard:
    enabled: true
security:
  basic:
    enabled: true #开启认证
  user:
    name: admin
    password: 123456