eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  dashboard:
    enabled: true
  instance:
    namespace: worken
    prefer-ip-address: false
  server:
    enable-self-preservation: false
    disable-transparent-fallback-to-other-region: true
logging:
  level: off
spring:
  redis:
    host: 192.168.0.156
    port: 6380
    database: 11
  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8