eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  dashboard:
    enabled: true
  instance:
    namespace: worken
    prefer-ip-address: false
  server:
    enable-self-preservation: false
    disable-transparent-fallback-to-other-region: true
logging:
  level: off
server:
  port: 8761 #eureka默认端口
spring:
  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8
ip-white-list:
  enable: false