server:
  port: 19999
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LubinXuan/spring_cloud_demo
          username: lubin.xuan@gmail.com
          password: xlb900907
          search-paths: config/repo
      token: e83c4e76c957da6b77580e3b8237ca7622443491